<?php
    /*
     * Sample Configuration File
     * Create config.inc and set your configurations
     */
    return array(
        'username' => '', // set your ideone username
        'password' => '', // set your ideone password
        'tempLocation' => __DIR__ . '/temp', // cache folder location
        'expiryTime' => '1', // cache expiry time in days
        'serverRoot' => '/Cloud-Compiler-API/', // server root used while routing
        'proxy' => '' // proxy server
    );