<?php
    /*
     * Data required for scraping the website
     * Modify only if there are scraping errors
     */
    return array(
        'mainLink' => 'https://ideone.com/',
        'loginLink' => 'https://ideone.com/account/login',
        'submissionLink' => 'https://ideone.com/ideone/Index/submit/',
        'ajaxSubLink1' => 'https://ideone.com/ideone/Index/view/id/',
        'ajaxSubLink2' => '/ajax/1/lp/1',
        'sourceCodeLink' => 'https://ideone.com/plain/',
        'langDropDownMenuID' => 'lang-dropdown-menu',
        'langPopularClass' => 'popular',
        'langRestClass' => 'rest',
        'langIdAttr' => 'data-id',
        'langLabelAttr' => 'data-label',
        'langTitleAttr' => 'title',
        'loginNavID' => 'primary-navigation',
        'loginSearch' => 'my account',
        'sessionID' => 'p1',
        'stdinID' => 'view_stdin',
        'stdinEmpty' => 'Standard input is empty',
        'infoID' => 'info',
        'strongTagLength' => 1,
        'dateID' => 'solution_date'
    );